// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUAvjO9GmpnslwueLtjqkzQaM7dL70YMc',
    appId: '1:831748049038:web:0e4cb95839dbfe8484e1df',
    messagingSenderId: '831748049038',
    projectId: 'crmmini-76d4a',
    authDomain: 'crmmini-76d4a.firebaseapp.com',
    storageBucket: 'crmmini-76d4a.firebasestorage.app',
    measurementId: 'G-YXK0DB2L9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKPm3Ug_L1KBkmV5A2CKY5caBIhQngc7o',
    appId: '1:831748049038:android:81a8c2cfb681a0db84e1df',
    messagingSenderId: '831748049038',
    projectId: 'crmmini-76d4a',
    storageBucket: 'crmmini-76d4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrY_e4JIf4pYJrt3VTaq6x6k5mGJtFdEI',
    appId: '1:831748049038:ios:c16ed9a8bad00d5f84e1df',
    messagingSenderId: '831748049038',
    projectId: 'crmmini-76d4a',
    storageBucket: 'crmmini-76d4a.firebasestorage.app',
    iosBundleId: 'com.example.crmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrY_e4JIf4pYJrt3VTaq6x6k5mGJtFdEI',
    appId: '1:831748049038:ios:c16ed9a8bad00d5f84e1df',
    messagingSenderId: '831748049038',
    projectId: 'crmmini-76d4a',
    storageBucket: 'crmmini-76d4a.firebasestorage.app',
    iosBundleId: 'com.example.crmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUAvjO9GmpnslwueLtjqkzQaM7dL70YMc',
    appId: '1:831748049038:web:03428d6f2adab92084e1df',
    messagingSenderId: '831748049038',
    projectId: 'crmmini-76d4a',
    authDomain: 'crmmini-76d4a.firebaseapp.com',
    storageBucket: 'crmmini-76d4a.firebasestorage.app',
    measurementId: 'G-CV2210WG95',
  );
}
