import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:crm_app/router/app_router.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

// Firebase Web Configuration
import 'firebase_options.dart'; // Automatically generated by FlutterFire CLI or manually configured

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase with the appropriate options
  await Firebase.initializeApp(
    options:
        DefaultFirebaseOptions
            .currentPlatform, // Ensure this is correct for your platform
  );
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: goRouter,
      debugShowCheckedModeBanner: false,
    );
  }
}
